name: Test Go project

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'
      tags:
        required: false
        type: string
        default: ''
      env_vars:
        required: false
        type: string
        default: ''

jobs:
  test:
    runs-on: docker 
    steps:
      - name: Checkout
        uses: https://git.yak-wall.ts.net/public/actions/checkout@master

      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: stable

      - name: Test
        run: |
          cd src;
          [ -n "${INPUTS_ENV_VARS}" ] && export ${INPUTS_ENV_VARS};
          go test -tags "${INPUTS_TAGS}" "${INPUTS_PACKAGE}"
        env:
          INPUTS_TAGS: ${{inputs.tags}}
          INPUTS_PACKAGE: ${{inputs.package}}
          INPUTS_ENV_VARS: ${{inputs.env_vars}}
