name: Test Go project

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'
      tags:
        required: false
        type: string
        default: ''

jobs:
  test:
    runs-on: docker 
    steps:
      - name: Checkout
        uses: https://git.yak-wall.ts.net/public/actions/checkout@master

      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: stable

      - name: Test
        run: |
          cd src;
          go test -tags "${INPUTS_TAGS}" "${INPUTS_PACKAGE}"
        env:
          INPUTS_TAGS: ${{inputs.tags}}
          INPUTS_PACKAGE: ${{inputs.package}}
