name: Check Go project for vulnerabilities

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'
      env_vars:
        required: false
        type: string
        default: ''
      apt_packages:
        required: false
        type: string
        default: ''

jobs:
  vulncheck:
    runs-on: docker 
    steps:
      - name: Checkout
        uses: https://git.yak-wall.ts.net/public/actions/checkout@master

      - name: Install Go
        uses: https://git.yak-wall.ts.net/public/actions/setupgo@master 

      - name: Install extra packages
        if: inputs.apt_packages != ''
        run: |
          apt-get update
          apt-get install -y ${INPUTS_APT_PACKAGES}
        env:
          INPUTS_APT_PACKAGES: ${{ inputs.apt_packages }}

      - name: Check for vulnerabilities
        run: |
          cd src;
          [ -n "${INPUTS_ENV_VARS}" ] && export ${INPUTS_ENV_VARS};
          go run golang.org/x/vuln/cmd/govulncheck@latest -- "${INPUTS_PACKAGE}"
        env:
          INPUTS_PACKAGE: ${{inputs.package}}
          INPUTS_ENV_VARS: ${{inputs.env_vars}}
