name: Check Go project for vulnerabilities

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'
      env_vars:
        required: false
        type: string
        default: ''

jobs:
  vulncheck:
    runs-on: docker 
    steps:
      - name: Checkout
        uses: https://git.yak-wall.ts.net/public/actions/checkout@master

      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: stable

      - name: Check for vulnerabilities
        run: |
          cd src;
          [ -n "${INPUTS_ENV_VARS}" ] && export ${INPUTS_ENV_VARS};
          go run golang.org/x/vuln/cmd/govulncheck@latest -- "${INPUTS_PACKAGE}"
        env:
          INPUTS_PACKAGE: ${{inputs.package}}
          INPUTS_ENV_VARS: ${{inputs.env_vars}}
