name: Check that a container builds

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
        default: 'Dockerfile'

jobs:
  docker:
    runs-on: docker 
    container:
      image: quay.io/buildah/stable
    steps:
      - name: Checkout
        uses: https://git.yak-wall.ts.net/public/actions/checkout@master

      - name: Do everything 
        run: |
          set -eux;
          cd src;
          sed -i 's/short-name-mode = "enforcing"/short-name-mode = "disabled"/g' /etc/containers/registries.conf;
          buildah bud -f "${{ inputs.dockerfile }}" --timestamp=0 --identity-label=false
