name: Check that a container builds

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
        default: 'Dockerfile'

jobs:
  docker:
    runs-on: docker 
    steps:

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Build image
        container:
          image: quay.io/buildah/stable:latest
        run: buildah bud "${{ inputs.dockerfile }}"
