name: Check that a container builds

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
        default: 'Dockerfile'

jobs:
  docker:
    runs-on: docker 
    steps:
      - name: Checkout
        uses: https://git.yak-wall.ts.net/public/actions/checkout@dev

      - name: Build
        uses: https://git.yak-wall.ts.net/public/actions/dockerbuild@dev
