name: Build and push container

permissions:
  contents: read
  packages: write

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
        default: 'Dockerfile'
      image:
        required: false
        type: string
        default: ${{ github.repository }}

jobs:
  docker:
    runs-on: docker 
    container:
      image: quay.io/buildah/stable
    steps:
      - name: Checkout
        run: |
          set -eux;
          mkdir -p "$FORGEJO_WORKSPACE";
          cd "$FORGEJO_WORKSPACE";
          export TOKEN=$(echo "${FORGEJO_REPOSITORY_OWNER}:${FORGEJO_TOKEN}" | base64);
          git -c "http.extraHeader=\"Authorization: Basic $TOKEN\"" clone "${FORGEJO_SERVER_URL}/${FORGEJO_REPOSITORY}" .;
          git checkout "${FORGEJO_REF_NAME}";

      - name: Build image
        id: build-image
        uses: https://github.com/redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          dockerfiles: ${{ inputs.dockerfile }}
          image: ${{ inputs.image }}
          tags: ${{ steps.tags.outputs.tags }}
          extra-args: >
            --timestamp
            0

      - name: Push to registry
        uses: https://github.com/redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: ${{ steps.build-image.outputs.image }}
          registry: forgejo.local 
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: latest # ${{ steps.tags.outputs.tags }}

