name: Build and push container

permissions:
  contents: read
  packages: write

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
        default: 'Dockerfile'
      image:
        required: false
        type: string
        default: ${{ github.repository }}
      github:
        required: false
        type: string
        default: ''

jobs:
  docker:
    runs-on: docker 
    steps:
      - name: Checkout
        uses: https://git.yak-wall.ts.net/public/actions/checkout@dev

      - name: Get tags
        id: tags
        uses: https://git.yak-wall.ts.net/public/actions/imagetags@dev

      - name: Login to forgejo
        uses: https://git.yak-wall.ts.net/public/actions/dockerlogin@dev
        with:
          registry: git.yak-wall.ts.net
          username: chris
          password: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

      - name: Login to GitHub
        uses: https://git.yak-wall.ts.net/public/actions/dockerlogin@dev
        if: ${{ inputs.github }}
        with:
          registry: ghcr.io
          username: csmith
          password: ${{ secrets.GH_REGISTRY_TOKEN }}

      - name: Build container
        uses: https://git.yak-wall.ts.net/public/actions/dockerbuild@dev

      - name: Push to forgejo 
        uses: https://git.yak-wall.ts.net/public/actions/dockerpush@dev
        with:
          name: git.yak-wall.ts.net/${{ inputs.image }}
          tags: ${{ steps.tags.outputs.tags }}

      - name: Push to GitHub
        uses: https://git.yak-wall.ts.net/public/actions/dockerpush@dev
        if: ${{ inputs.github }}
        with:
          name: ghcr.io/${{ inputs.github }}
          tags: ${{ steps.tags.outputs.tags }}
